Traceback (most recent call last):
  File "caculate_interaction.py", line 27, in <module>
    for line in open(file1[0]):
IndexError: list index out of range
